### ISSUE TITLE
Cancel Renew lock throws error in the interceptor

### ISSUE THREAD

**Issue by marcodalessandro** [princjef/irontask#11]
https://github.com/princjef/irontask/blob/5eabec4ee89a9652ccd723515866fa56a3cdb295/src/task/active.ts#L596-L601

**Comment by princjef** [comment]
It would help if I followed my own TODOs. I'll figure out how to get the cancellation notification out of the operation so that it doesn't throw an error.

This check is also invalid with interceptors present because the interceptor can transform the error such that it doesn't match in the check we're doing here.

**Comment by marcodalessandro** [comment]
Thanks, it is not actually causing any issue but only some noise in our logs.
